version: '3'

services:

# Setup DB container
  db:
    image: postgres:latest
    container_name: db-app-node-18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-typescript
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

# Setup API container
  app:
      container_name: app-node-18
      restart: always
      build: .
      ports:
          - "3000:3000"
      depends_on:
          - db
