version: '3.9'

services:

# Setup MYSQL container
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

# Setup app container
  app:
    build:
     context: .
     dockerfile: Dockerfile
    #build: ./app
    container_name: app-node-18
    restart: always
    depends_on:
      - mysql
    env_file: ./.env
    ports:
      - "${APP_PORT}:3000"
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    networks:
      - backend

volumes:
  mysql-data:
networks:
  backend: